name: cadmean_rpc
description: A Cadmean RPC library for Dart. Its goal is to simplify the communication with your web API, hiding all the HTTP and JSON stuff.
version: 0.1.1
repository: https://github.com/cadmean-ru/cadmean_rpc_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.10.0
  test: 
