name: cadmean_rpc
description: A Cadmean RPC library for Dart.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http:

dev_dependencies:
  pedantic: ^1.10.0
  test:
